---

- name: Set user info for showroom
  agnosticd_user_info:
    user: "user"
    data:
      user_name: "user"
      user_password: "{{ common_password }}"
      common_password: "{{ common_password }}"
      openshift_cluster_console: "https://{{ r_console_route.resources[0].spec.host }}"
      openshift_cluster_console_url: "{{ r_openshift_subdomain }}"
      openshift_cluster_ingress_domain: "{{ r_openshift_subdomain }}"


- name: Install Showroom
  ansible.builtin.include_role:
    name: ocp4_workload_showroom
  vars:
    ocp4_workload_showroom_deployment_type: "{{ ocp4_workload_pe_workshop_showroom_deployment_type }}"
    ocp4_workload_showroom_content_git_repo: "{{ ocp4_workload_pe_workshop_showroom_content_git_repo }}"
    ocp4_workload_showroom_content_git_repo_ref: "{{ ocp4_workload_pe_workshop_showroom_content_git_repo_ref }}"
    ocp4_workload_showroom_content_only: "{{ ocp4_workload_pe_workshop_showroom_content_only }}"
    ocp4_workload_showroom_namespace: "{{ ocp4_workload_pe_workshop_showroom_namespace }}"
    ocp4_workload_showroom_deployer_chart_version: "{{ ocp4_workload_pe_workshop_showroom_deployer_chart_version }}"
